# Generated by Django 4.2.16 on 2025-10-29 20:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnaliseLevedura",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nome_amostra", models.CharField(blank=True, max_length=200)),
                ("descricao", models.TextField(blank=True)),
                ("usuario", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("processando", "Processando"),
                            ("concluido", "Concluído"),
                            ("erro", "Erro"),
                        ],
                        default="pendente",
                        max_length=20,
                    ),
                ),
                ("resultado", models.JSONField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(default=django.utils.timezone.now)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ImagemMicroscopica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "imagem",
                    models.ImageField(upload_to="leveduras/microscopicas/%Y/%m/%d/"),
                ),
                ("metadata", models.JSONField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "status_processamento",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("processando", "Processando"),
                            ("concluido", "Concluído"),
                            ("erro", "Erro"),
                        ],
                        default="pendente",
                        max_length=20,
                    ),
                ),
                ("progresso", models.IntegerField(default=0)),
                ("erro_processamento", models.TextField(blank=True, null=True)),
                ("task_id", models.CharField(blank=True, max_length=255, null=True)),
                ("iniciado_em", models.DateTimeField(blank=True, null=True)),
                ("concluido_em", models.DateTimeField(blank=True, null=True)),
                (
                    "analise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imagens_microscopicas",
                        to="leveduras.analiselevedura",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LeveduraSegmentada",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "levedura_id",
                    models.IntegerField(help_text="ID da levedura na segmentação"),
                ),
                (
                    "imagem",
                    models.ImageField(
                        max_length=500, upload_to="leveduras_segmentadas/%Y/%m/%d/"
                    ),
                ),
                ("nome_arquivo", models.CharField(max_length=255)),
                (
                    "bounding_box",
                    models.JSONField(
                        help_text="Coordenadas da bounding box {x, y, width, height}"
                    ),
                ),
                ("metadata", models.JSONField(default=dict)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "analise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leveduras_segmentadas",
                        to="leveduras.analiselevedura",
                    ),
                ),
                (
                    "imagem_original",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leveduras_segmentadas",
                        to="leveduras.imagemmicroscopica",
                    ),
                ),
            ],
            options={
                "db_table": "leveduras_segmentadas",
                "ordering": ["levedura_id"],
            },
        ),
        migrations.CreateModel(
            name="ImagemColonia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imagem", models.ImageField(upload_to="leveduras/colonias/%Y/%m/%d/")),
                ("metadata", models.JSONField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "analise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imagens_colonias",
                        to="leveduras.analiselevedura",
                    ),
                ),
            ],
        ),
    ]
