# Generated by Django 4.2.16 on 2025-10-29 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leveduras", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="levedurasegmentada",
            name="area_microns",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="levedurasegmentada",
            name="area_pixels",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="levedurasegmentada",
            name="caracteristicas",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="levedurasegmentada",
            name="circularidade",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="levedurasegmentada",
            name="diametro_equivalente",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="levedurasegmentada",
            name="relacao_aspecto",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="levedurasegmentada",
            name="solidez",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
